
export const SESSION_PREFIX = "baaw_commerce_";
export const SESSION_USER = "user";

export const AUTH_HEADER = "Authorization";

export const SHA_CRIPT_STRING = "ou98y7t6rdfcgvhui89765rtfyghui89y7t6fyghui";

export const PAYMENT_METHOD_PAYPAL = "PAYPAL";

export const TRANSACT_STATUS_BEFORE_TRANSACTION = "BEFORE_TRANSACTION";
export const TRANSACT_STATUS_CANCEL_TRANSACTION = "CANCEL_TRANSACTION";
export const TRANSACT_STATUS_CLIENT_AUTHORIZATION = "CLIENT_AUTHORIZATION";

export const TRANSACT_STATUS_AFTER_TRANSACTION_APPROVED = "APPROVED_NOT_AUTHORIZE_YET";
export const TRANSACT_STATUS_AFTER_TRANSACTION_APPROVED_AND_AUTHORIZED = "APPROVED_AND_AUTHORIZED";
export const TRANSACT_STATUS_AFTER_TRANSACTION_FAILED = "AFTER_TRANSACTION_FAILED";
export const TRANSACT_STATUS_USER_VENDOR_NOTIFIED = "USER_VENDOR_NOTIFIED";
export const TRANSACT_STATUS_USER_SALER_NOTIFIED = "USER_SALER_NOTIFIED";
export const TRANSACT_STATUS_USER_ADMINISTRATORS_NOTIFIED = "USER_ADMINISTRATORS_NOTIFIED";
export const TRANSACT_STATUS_USER_VENDOR_INCLUSE_TRACK_ID = "USER_VENDOR_INCLUSE_TRACK_ID";

export const WEB_SITE_PAYPAL_PERCENTAJE = .03;
export const WEB_SITE_TAX = .0;

export const PROFILE_BAAW_PARTNER = "BAAW_PARTNER";
